[package]
name = "python_bindings"
version = "0.1.0"
edition = "2021"

[lib]
name = "coreml"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25.1", features = ["extension-module"] }
loader = { path = "../loader" }
