[package]
name = "linear_regression"
version = "0.1.0"
edition = "2024"

[dependencies]
linear_algebra = { path = "../linear_algebra/" }
loader = { path = "../loader/" }

[dev-dependencies]
notes = { path = "../notes/" }
